package Forms;

import Project.ConnectionProvider;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hi
 */
public class DropData extends javax.swing.JFrame {

    /**
     * Creates new form DropData
     */
    public DropData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dropBtn = new javax.swing.JButton();
        dropId = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));
        setLocation(new java.awt.Point(510, 220));
        setMinimumSize(new java.awt.Dimension(429, 260));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropBtn.setBackground(new java.awt.Color(204, 255, 255));
        dropBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dropBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return book png.png"))); // NOI18N
        dropBtn.setText("Drop");
        dropBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dropBtnMouseClicked(evt);
            }
        });
        dropBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropBtnActionPerformed(evt);
            }
        });
        getContentPane().add(dropBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        dropId.setBackground(new java.awt.Color(255, 255, 204));
        dropId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dropId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropIdActionPerformed(evt);
            }
        });
        getContentPane().add(dropId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 230, 37));

        cancelBtn.setBackground(new java.awt.Color(255, 51, 51));
        cancelBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(" ENTER ID #");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -170, 610, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dropIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropIdActionPerformed
       
    }//GEN-LAST:event_dropIdActionPerformed

    private void dropBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropBtnActionPerformed

    private void dropBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropBtnMouseClicked
       
        dropdata();
    }//GEN-LAST:event_dropBtnMouseClicked

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
       
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnMouseClicked
  public void dropdata() {
        int a = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?", "Message", JOptionPane.YES_NO_OPTION);

        if (a == 0) {

        try {
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","");  
            //Connection con = DriverManager.getConnection("jdbc:mysql://192.168.0.83/telezmidterm-ais", "ais-sd204", "password");
            //Connection con = DriverManager.getConnection("jdbc:mysql://192.168.0.27/ramilmidterm-ais", "sd204-AIS", "password");
            Connection con = ConnectionProvider.getCon();
            Statement stmt = con.createStatement();

            String query = "DELETE FROM student WHERE studentID ='" + this.dropId.getText() + "'";
            stmt.execute(query);
            con.close();
          
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "Successfully Dropped!", "Alert", JOptionPane.WARNING_MESSAGE);
        } catch (HeadlessException | SQLException e) {
            System.out.println(e);
        }

    }
  }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DropData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DropData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DropData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DropData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DropData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton dropBtn;
    private javax.swing.JTextField dropId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
