package Forms;


//import Forms.IssueBook;
//import Forms.Login;
//import Forms.NewBook;
//import Forms.NewStudent;
//import Forms.ReturnBook;
//import Forms.Statistics;



public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newStudentBtn = new javax.swing.JButton();
        newBookBtn = new javax.swing.JButton();
        statisticsBtn = new javax.swing.JButton();
        issueBookBtn = new javax.swing.JButton();
        returnBookBtn = new javax.swing.JButton();
        homeLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newStudentBtn.setBackground(new java.awt.Color(223, 255, 253));
        newStudentBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newStudentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/member-add-on-300x300.png"))); // NOI18N
        newStudentBtn.setText("New Student");
        newStudentBtn.setMaximumSize(new java.awt.Dimension(169, 59));
        newStudentBtn.setMinimumSize(new java.awt.Dimension(169, 59));
        newStudentBtn.setPreferredSize(new java.awt.Dimension(169, 59));
        newStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newStudentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        newBookBtn.setBackground(new java.awt.Color(223, 255, 253));
        newBookBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/New book.png"))); // NOI18N
        newBookBtn.setText("New Book");
        newBookBtn.setMaximumSize(new java.awt.Dimension(169, 59));
        newBookBtn.setMinimumSize(new java.awt.Dimension(169, 59));
        newBookBtn.setPreferredSize(new java.awt.Dimension(169, 59));
        newBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 200, -1, -1));

        statisticsBtn.setBackground(new java.awt.Color(223, 255, 253));
        statisticsBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statisticsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Statics.png"))); // NOI18N
        statisticsBtn.setText("Statistics");
        statisticsBtn.setMaximumSize(new java.awt.Dimension(169, 59));
        statisticsBtn.setMinimumSize(new java.awt.Dimension(169, 59));
        statisticsBtn.setPreferredSize(new java.awt.Dimension(169, 59));
        statisticsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(statisticsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        issueBookBtn.setBackground(new java.awt.Color(223, 255, 253));
        issueBookBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        issueBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/issue.png"))); // NOI18N
        issueBookBtn.setText("Issue Book");
        issueBookBtn.setMaximumSize(new java.awt.Dimension(169, 59));
        issueBookBtn.setMinimumSize(new java.awt.Dimension(169, 59));
        issueBookBtn.setPreferredSize(new java.awt.Dimension(169, 59));
        issueBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookBtnActionPerformed(evt);
            }
        });
        getContentPane().add(issueBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 420, -1, -1));

        returnBookBtn.setBackground(new java.awt.Color(223, 255, 253));
        returnBookBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        returnBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return-book-1-560407.png"))); // NOI18N
        returnBookBtn.setText("Return Book");
        returnBookBtn.setMaximumSize(new java.awt.Dimension(169, 59));
        returnBookBtn.setMinimumSize(new java.awt.Dimension(169, 59));
        returnBookBtn.setPreferredSize(new java.awt.Dimension(169, 59));
        returnBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookBtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, -1, -1));

        homeLogout.setBackground(new java.awt.Color(223, 255, 253));
        homeLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        homeLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        homeLogout.setText("Log Out");
        homeLogout.setMaximumSize(new java.awt.Dimension(169, 59));
        homeLogout.setMinimumSize(new java.awt.Dimension(169, 59));
        homeLogout.setPreferredSize(new java.awt.Dimension(169, 59));
        homeLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(homeLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 580, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1420, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentBtnActionPerformed
        new NewStudent().setVisible(true);
    }//GEN-LAST:event_newStudentBtnActionPerformed

    private void statisticsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsBtnActionPerformed
//        new Statistics().setVisible(true);
    }//GEN-LAST:event_statisticsBtnActionPerformed

    private void issueBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookBtnActionPerformed
        new IssueBook().setVisible(true);
    }//GEN-LAST:event_issueBookBtnActionPerformed

    //for home logout
    private void homeLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeLogoutActionPerformed
       setVisible(false);
       new Login().setVisible(true);
        
    }//GEN-LAST:event_homeLogoutActionPerformed

    //for new book button
    private void newBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookBtnActionPerformed
        new NewBook().setVisible(true);
    }//GEN-LAST:event_newBookBtnActionPerformed
    //for return book home button
    private void returnBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookBtnActionPerformed
        new ReturnBook().setVisible(true);
    }//GEN-LAST:event_returnBookBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeLogout;
    private javax.swing.JButton issueBookBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton newBookBtn;
    private javax.swing.JButton newStudentBtn;
    private javax.swing.JButton returnBookBtn;
    private javax.swing.JButton statisticsBtn;
    // End of variables declaration//GEN-END:variables
}
