package Forms;


import java.text.SimpleDateFormat;
import Project.ConnectionProvider;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hi
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        bookID = new javax.swing.JLabel();
        studentID = new javax.swing.JLabel();
        issueDate = new javax.swing.JLabel();
        dueDate = new javax.swing.JLabel();
        bookIDField = new javax.swing.JTextField();
        studentIDField = new javax.swing.JTextField();
        issueDateField = new com.toedter.calendar.JDateChooser();
        dueDateField = new com.toedter.calendar.JDateChooser();
        closeBtn = new javax.swing.JButton();
        issueBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bookID.setText("Book ID     :");
        getContentPane().add(bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 120, -1));

        studentID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        studentID.setText("Student ID:");
        getContentPane().add(studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 120, -1));

        issueDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        issueDate.setText("Issue Date:");
        getContentPane().add(issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 120, -1));

        dueDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dueDate.setText("Due Date  :");
        getContentPane().add(dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 110, -1));

        bookIDField.setBackground(new java.awt.Color(255, 255, 204));
        bookIDField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bookIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIDFieldActionPerformed(evt);
            }
        });
        getContentPane().add(bookIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 250, 30));

        studentIDField.setBackground(new java.awt.Color(255, 255, 204));
        studentIDField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        studentIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDFieldActionPerformed(evt);
            }
        });
        getContentPane().add(studentIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 250, 30));

        issueDateField.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(issueDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 250, 30));

        dueDateField.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(dueDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 250, 30));

        closeBtn.setBackground(new java.awt.Color(153, 255, 153));
        closeBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red-x-mark-transparent-background-3.png"))); // NOI18N
        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 110, 40));

        issueBtn.setBackground(new java.awt.Color(153, 255, 153));
        issueBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        issueBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/issue book.png"))); // NOI18N
        issueBtn.setText("Issue");
        issueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBtnActionPerformed(evt);
            }
        });
        getContentPane().add(issueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/allbg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIDFieldActionPerformed

    private void studentIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDFieldActionPerformed

    //for issue button
    private void issueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBtnActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("MM-dd-yyyy");
        String bookID = bookIDField.getText();
        String studentID = studentIDField.getText();
        String issueDate = dateFormat.format(issueDateField.getDate());
        String dueDate = dateFormat.format(dueDateField.getDate());
        String returnBook = "No";
      
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet resSet = st.executeQuery("select * from books where bookID='"+bookID+"'");
            if(resSet.next()){
                ResultSet resSet1 = st.executeQuery("select * from student where studentID='"+studentID+"'");
                if(resSet1.next()){
                    st.executeUpdate("insert into issuebook values('"+bookID+"','"+studentID+"','"+issueDate+"','"+dueDate+"','"+returnBook+"')");
                    JOptionPane.showConfirmDialog(null,"Book Succesfully Issued!");
                    setVisible(false);
                    new IssueBook().setVisible(true);
                }else{
                    JOptionPane.showConfirmDialog(null,"Incorrect Student ID!");
                }
            }else{
                JOptionPane.showConfirmDialog(null,"Incorrect Book ID!");
            }
        }catch(HeadlessException | SQLException e){
            
          JOptionPane.showConfirmDialog(null,"Connection Error!");
        }
    }//GEN-LAST:event_issueBtnActionPerformed

    //for close button
    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookID;
    private javax.swing.JTextField bookIDField;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel dueDate;
    private com.toedter.calendar.JDateChooser dueDateField;
    private javax.swing.JButton issueBtn;
    private javax.swing.JLabel issueDate;
    private com.toedter.calendar.JDateChooser issueDateField;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel studentID;
    private javax.swing.JTextField studentIDField;
    // End of variables declaration//GEN-END:variables
}
