/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;
import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import  javax.swing.border.Border;
/**
 *
 * @author hi
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
         fetch_data();
    }
       //to get the data from the database and display on the table
    public void fetch_data() {
        DefaultTableModel dm;
        dm = (DefaultTableModel) studentList.getModel();

        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            String sql = "select * from student";
            ResultSet rs = st.executeQuery(sql);
            studentList.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        courseCombo = new javax.swing.JComboBox<>();
        studentIDField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        branchCombo = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentList = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(270, 70));
        setMaximumSize(new java.awt.Dimension(1095, 710));
        setMinimumSize(new java.awt.Dimension(1095, 710));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1095, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(233, 246, 250));
        jPanel1.setMaximumSize(new java.awt.Dimension(1095, 710));
        jPanel1.setMinimumSize(new java.awt.Dimension(1095, 710));
        jPanel1.setPreferredSize(new java.awt.Dimension(1095, 710));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Student ID     :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 70, 131, 22);

        firstNameField.setBackground(new java.awt.Color(233, 246, 250));
        firstNameField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstNameField.setBorder(null);
        firstNameField.setPreferredSize(new java.awt.Dimension(200, 20));
        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(firstNameField);
        firstNameField.setBounds(510, 120, 270, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("First Name      :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(340, 130, 134, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Last Name      :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 190, 132, 22);

        lastNameField.setBackground(new java.awt.Color(233, 246, 250));
        lastNameField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastNameField.setBorder(null);
        lastNameField.setPreferredSize(new java.awt.Dimension(200, 20));
        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(lastNameField);
        lastNameField.setBounds(510, 180, 270, 40);

        courseCombo.setBackground(new java.awt.Color(255, 255, 204));
        courseCombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        courseCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Formal Sciences", "asd" }));
        courseCombo.setBorder(null);
        courseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboActionPerformed(evt);
            }
        });
        jPanel1.add(courseCombo);
        courseCombo.setBounds(490, 240, 270, 40);

        studentIDField.setBackground(new java.awt.Color(233, 246, 250));
        studentIDField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studentIDField.setBorder(null);
        studentIDField.setPreferredSize(new java.awt.Dimension(200, 20));
        studentIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDFieldActionPerformed(evt);
            }
        });
        jPanel1.add(studentIDField);
        studentIDField.setBounds(510, 60, 270, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Course Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 250, 133, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Branch Name :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(340, 300, 135, 22);

        branchCombo.setBackground(new java.awt.Color(255, 255, 204));
        branchCombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        branchCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT", "BSCS", "BSIS", "BS Mathematics", " " }));
        branchCombo.setBorder(null);
        jPanel1.add(branchCombo);
        branchCombo.setBounds(490, 300, 270, 40);

        addBtn.setBackground(new java.awt.Color(0, 0, 0));
        addBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addBtn.setText("ADD");
        addBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));
        addBtn.setContentAreaFilled(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn);
        addBtn.setBounds(400, 410, 120, 40);

        closeBtn.setBackground(new java.awt.Color(153, 255, 153));
        closeBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red-x-mark-transparent-background-3.png"))); // NOI18N
        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(closeBtn);
        closeBtn.setBounds(910, 50, 120, 40);

        studentList.setBackground(new java.awt.Color(204, 255, 204));
        studentList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "studentID", "firstName", "middleName", "lastName", "courseName", "branchName"
            }
        ));
        studentList.setGridColor(new java.awt.Color(255, 255, 255));
        studentList.setSelectionBackground(new java.awt.Color(0, 51, 51));
        studentList.setSelectionForeground(new java.awt.Color(0, 255, 0));
        studentList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentListMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                studentListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(studentList);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(170, 490, 860, 100);

        updateBtn.setBackground(new java.awt.Color(153, 255, 153));
        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminIcons/icons8_Exit_26px_1.png"))); // NOI18N
        updateBtn.setText("UPDATE");
        updateBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));
        updateBtn.setContentAreaFilled(false);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn);
        updateBtn.setBounds(540, 410, 140, 40);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jPanel5);
        jPanel5.setBounds(500, 100, 250, 2);

        deleteBtn.setBackground(new java.awt.Color(153, 255, 153));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red-x-mark-transparent-background-3.png"))); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn);
        deleteBtn.setBounds(710, 410, 130, 40);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(140, 10, 190, 0);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jPanel3);
        jPanel3.setBounds(500, 160, 250, 2);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jPanel6);
        jPanel6.setBounds(500, 220, 250, 2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1095, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void courseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseComboActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String studentID = studentIDField.getText();
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();
        String courseName = (String) courseCombo.getSelectedItem();
  
        String branchName = (String) branchCombo.getSelectedItem();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("insert into student values('" + studentID + "','" + firstName + "','" + lastName + "','" + courseName + "','" + branchName + "')");
            JOptionPane.showMessageDialog(null, "Successfully Updated!");
            setVisible(false);
            new NewStudent().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Student ID Already Exist!");
            setVisible(false);
            new Dashboard().setVisible(true);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void studentIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDFieldActionPerformed

    private void studentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentListMouseClicked

        String studentId;
        String firstName;
        String lastName;
        String courseName;
        String branchName;
        int row = studentList.getSelectedRow();
        studentId = (studentList.getModel().getValueAt(row, 0).toString());
        firstName = (studentList.getModel().getValueAt(row, 1).toString());
        lastName = (studentList.getModel().getValueAt(row, 2).toString());
        courseName = (studentList.getModel().getValueAt(row, 3).toString());
        branchName = (studentList.getModel().getValueAt(row, 4).toString());
        branchCombo.setSelectedItem(branchName);

        studentIDField.setText(studentId);
        firstNameField.setText(firstName);
        lastNameField.setText(lastName);
        courseCombo.getSelectedItem();
//        branchCombo.getSelectedItem();
    }//GEN-LAST:event_studentListMouseClicked

    private void studentListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentListMousePressed

    }//GEN-LAST:event_studentListMousePressed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox<String> branchCombo;
    private javax.swing.JButton closeBtn;
    private javax.swing.JComboBox<String> courseCombo;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField studentIDField;
    private javax.swing.JTable studentList;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
