package Forms;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hi
 */
public class UpdateForm extends javax.swing.JFrame {

    /**
     * Creates new form UpdateForm
     */
    public UpdateForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookIDField = new javax.swing.JTextField();
        bookIDField1 = new javax.swing.JTextField();
        bookIDField2 = new javax.swing.JTextField();
        bookIDField3 = new javax.swing.JTextField();
        bookIDField4 = new javax.swing.JTextField();
        bookIDField5 = new javax.swing.JTextField();
        bookIDField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookIDField.setBackground(new java.awt.Color(255, 255, 204));
        bookIDField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIDFieldActionPerformed(evt);
            }
        });
        getContentPane().add(bookIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 240, 30));

        bookIDField1.setBackground(new java.awt.Color(255, 255, 204));
        bookIDField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookIDField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIDField1ActionPerformed(evt);
            }
        });
        getContentPane().add(bookIDField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 240, 30));

        bookIDField2.setBackground(new java.awt.Color(255, 255, 204));
        bookIDField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookIDField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIDField2ActionPerformed(evt);
            }
        });
        getContentPane().add(bookIDField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 240, 30));

        bookIDField3.setBackground(new java.awt.Color(255, 255, 204));
        bookIDField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookIDField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIDField3ActionPerformed(evt);
            }
        });
        getContentPane().add(bookIDField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 240, 30));

        bookIDField4.setBackground(new java.awt.Color(255, 255, 204));
        bookIDField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookIDField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIDField4ActionPerformed(evt);
            }
        });
        getContentPane().add(bookIDField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 240, 30));

        bookIDField5.setBackground(new java.awt.Color(255, 255, 204));
        bookIDField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookIDField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIDField5ActionPerformed(evt);
            }
        });
        getContentPane().add(bookIDField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 240, 30));

        bookIDField6.setBackground(new java.awt.Color(255, 255, 204));
        bookIDField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookIDField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIDField6ActionPerformed(evt);
            }
        });
        getContentPane().add(bookIDField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 240, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("First Name       :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Branch Name  :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Middle Name    :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Last Name        :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Book ID            :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Book Name      :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Course Name  :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SAVE");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 460));

        jButton2.setText("SAVE");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIDFieldActionPerformed

    private void bookIDField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIDField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIDField1ActionPerformed

    private void bookIDField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIDField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIDField2ActionPerformed

    private void bookIDField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIDField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIDField3ActionPerformed

    private void bookIDField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIDField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIDField4ActionPerformed

    private void bookIDField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIDField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIDField5ActionPerformed

    private void bookIDField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIDField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIDField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookIDField;
    private javax.swing.JTextField bookIDField1;
    private javax.swing.JTextField bookIDField2;
    private javax.swing.JTextField bookIDField3;
    private javax.swing.JTextField bookIDField4;
    private javax.swing.JTextField bookIDField5;
    private javax.swing.JTextField bookIDField6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
